# Generated by Django 4.2.6 on 2023-11-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studeny',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
